version: "3.9"
services:
  coraza:
    build:
      dockerfile: docker/coraza-spoa/Dockerfile
      target: coreruleset
      args:
        - CORERULESET_DOWNLOAD=true
        - CORERULESET_VERSION=3.3.2
    #volumes:
    #  - type: bind
    #    source: ./docker/coraza-spoa
    #    target: /etc/coraza-spoa

  haproxy:
    image: haproxy:2.6-bullseye
    ports: [ "4000:80", "4443:443", "4001:4001" ]
    links:
      - "coraza:coraza"
      - "mockserv:mockserv"
    volumes:
      - type: bind
        source: ./docker/haproxy
        target: /usr/local/etc/haproxy

  mockserv:
    image: golang:1.18-bullseye
    command: go run /mockserv.go
    volumes:
      - type: bind
        source: ./contrib/mockserv.go
        target: /mockserv.go
