---
name: Docker Build

on:
  push:
    branches:
      - main
      - docker_build
      - docker_build2
    tags:
      - 'v*.*.*'

jobs:
  docker:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker buildx build --tag ghcr.io/sts/coraza-spoa --platform linux/amd64,linux/arm64,linux/arm/v7 --progress plain --push .

      - name: Build Image (CRS3)
        run: docker buildx build --progress plain --tag ghcr.io/sts/coraza-spoa:crs-3.3.2 --build-arg CORERULESET_VERSION=3.3.2 --platform linux/amd64,linux/arm64,linux/arm/v7 --target coreruleset --push .

      - name: Build Image (CRS4)
        run: docker buildx build --progress plain --tag ghcr.io/sts/coraza-spoa:crs-4.0.0-rc1 --build-arg CORERULESET_VERSION=4.0.0-rc1 --platform linux/amd64,linux/arm64,linux/arm/v7 --target coreruleset --push .


      #- name: Docker
      #  run: ./docker-build.sh ${DOCKER_VERSION} --push
      #  env:
      #    DOCKER_REGISTRY: "ghcr.io"
      #    DOCKER_ORG: "sts"
      #    DOCKER_REPO: "coraza-spoa"
