---
name: docker

on:
  push:
    branches:
      - main
      - docker_build
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build binary
        run: VERSION=${PACKAGE_VERSION} ARCH=${{ matrix.arch }} make

      - name: Docker
        run: ./docker-build.sh
        env:
          DOCKER_REGISTRY: "ghcr.io"
          DOCKER_ORG: "sts"
          DOCKER_REPO: "coraza-spoa"
